language: scala
sudo: false

matrix:
  include:
   - scala: 2.11
   - scala: 2.12
     env: EXECUTE_EXAMPLES=true
  fast_finish: true

cache:
  directories:
  - "$HOME/.m2"

before_cache:
- rm -rf $HOME/.m2/repository/io/cucumber

before_install:
- |
  export MODULES_TO_RUN="scala/scala_"$(echo $TRAVIS_SCALA_VERSION | sed -e 's/\([0-9]*\.[0-9]*\)\..*/\1/')
  [[ $EXECUTE_EXAMPLES = true ]] && export MODULES_TO_RUN=$MODULES_TO_RUN",examples"
  echo $MODULES_TO_RUN

install:
- mvn install -pl $MODULES_TO_RUN -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn test -pl $MODULES_TO_RUN -B
